- hosts: tag_Name_kubernetes_master
  become: yes
  gather_facts: false
  tasks:
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

- hosts: tag_Name_kubernetes_minion
  become: yes
  tasks:

    - name: Copy the join command to server location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777

    - name: Join the node to cluster
      command: sh /tmp/join-command.sh


